---
title: "Growth_Starting_Values"
author: "Derek H. Ogle"
date: "`r Sys.Date()`"
format: 
  html: 
    toc: true
    toc-depth: 2
    code-fold: true
    reference-location: margin
    fig-cap-location: bottom
    tbl-cap-location: top
    code-summary: "Show Code"
    echo: false
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---

```{r}
#| label: setup
#| results: hide
#| message: false
library(FSA)
```

# von Bertalanffy (Brody)
Blah-Blah-Blah

## Annual Length-at-Age Models
### The Parametrizations
`FSA` provides a wide variety of von Bertalanffy parameterizations for modeling simple length-at-age data (@tbl-VBparams1).

| param | Equation $L =$ |
|-------|-----------------------------------------------------|
|   1   | $L_\infty\left(1-e^{-K(t-t_0)}\right)$ |
|   2   | $L_\infty - (L_\infty-L_0)~e^{-Kt}$ |
|   3   | $\frac{\omega}{K}\left(1-e^{-K(t-t_0)}\right)$ |
|   4   | $L_\infty - (L_\infty-L_0)~e^{-\frac{\omega}{L_\infty}t}$ |
|   5   | $L_\infty\left(1-e^{-log(2)\frac{t-t_0}{t_{50}-t_0}}\right)$ |
|   6   | $L_r + (L_\infty-L_r)~e^{-e^{-K(t-t_r)}}$ |
|   7   | $L_1+(L_3-L_1)\frac{1-e^{-K(t-t_1)}}{1-e^{-K(t_3-t_1)}}$ |
|   8   | $L_1+(L_3-L_1)\frac{1-r^{2\frac{t-t_1}{t_3-t_1}}}{1-r^2}$ with $r=\frac{L_3-L_2}{L_2-L_1}$|
|   9   | $L_\infty\frac{\left(1-e^{-K_2(t-t_0)}\right)\left(1+e^{-b(t-t_0-a)}\right)}{\left(1+e^{ab}\right)^{-\frac{K_2K_1}{b}}}$

: Parameterizations of the von Bertalanffy growth equation for length-at-age data available in `FSA`. {#tbl-VBparams1}

<br>

The response variable, $L$, is the mean length and the explanatory variable, $t$ is age. Parameters in these growth functions are:

- $L_\infty$ = asymptotic mean length
- $K$ = exponential rate of approach to $L_\infty$
- $t_0$ = hypothetical time/age when mean length is 0
- $L_0$ = mean length at age-0 (i.e., hatching or birth)
- $\omega$ = growth rate near $t_0$
- $t_{50}$ = age when half of $L_\infty$ is reached
- $t_r$ = mean age at $L_r$ (*sometimes this is a constant*)
- $L_r$ = mean length at $t_r$ (*sometimes this is a constant*)
- $L_1$ = mean length at $t_1$ (generally a younger age)
- $L_2$ = mean length at $t_2$ (generally an intermediate age)
- $L_3$ = mean length at $t_3$ (generally a older age)
- $K_1$ = first exponential rate of approach to $L_\infty$
- $K_2$ = second exponential rate of approach to $L_\infty$
- $b$ = controls rate of transition from $K_1$ to $K_2$
- $a$ = central age of transition from $K_1$ to $K_2$


Constant values (i.e., set by the user) are:
- $t_r$ = mean age at $L_r$ (*sometimes this is a parameter*)
- $L_r$ = mean length at $t_r$ (*sometimes this is a parameter*)
- $t_1$ = a younger (generally) age
- $t_2$ = an age halfway between $t_1$ and $t_2$
- $t_3$ = an older (generally) age

### Starting Values
The `stats` package in base R contains `SSasymp()` which is a self-starting function for using `nls()` to fit an "asymptotic regression" function to data. According to the documentation for `SSasymp()` the parameterization of this function is

$$ Y = \text{Asym}+(\text{R0}-\text{Asym})~e^{-e^{\text{lrc}\times\text{input}}} $$

where $Y$ and $\text{input}$ are the response and explanatory variables, respectively, $\text{Asym}$ is a parameter for the horizontal (i.e., $Y$) asymptote, $\text{R0}$ is a parameter related to the value of $Y$ at $X=0$, and $lrc$ is a "parameter representing the natural logarithm of the rate constant."

In growth (in length) modeling, $Y$ is $L$ (for length); $\text{input}$ is $t$ (for time as measured by age); $\text{Asym}$ is clearly $L_{\infty}$, the asympotic mean length; and $\text{R0}$ is clearly $L_0$, the mean length at $t=0$ (i.e., the y-intercept). Thus, at this point, the R "asymptotic regression" function can be re-written for the purposes of growth modeling as 

$$ L = L_\infty - (L_\infty-L_0)~e^{-e^{\text{lrc}\times t}} $$

If we move $\text{lrc}$ off of the log scale by defining $K=e^{\text{lrc}}$, i.e., the Brody growth coefficient, we can further write this function as

$$ L = L_\infty - (L_\infty-L_0)~e^{-Kt} $$ {#eq-rSSasymp}

@eq-rSSasymp is **exactly** the second parameterization of the von Bertalanffy growth function in `FSA`.^[This is von Bertalanffy's original parameterization.] Thus, the starting values produced by `SSasymp()` can be used to find starting values for the second parameterization of the von Bertalanffy growth function in `FSA` (@tbl-VBstarts1). Indeed these values can be used for all parameterizations that use $L_\infty$, $L_0$, and $K$. Starting values for other parameters in other parameterizations can also be derived from these values.

A starting value for $t_0$, the "hypothetical time when the mean length is zero", is derived by setting $L=0$ in @eq-rSSasymp and solving for $t$.

$$
\begin{align}
0 &= L_\infty - (L_\infty-L_0)~e^{-Kt}  \\
L_\infty  &= (L_\infty-L_0)~e^{-Kt}  \\
\frac{L_\infty}{L_\infty-L_0} &= e^{-Kt}  \\
log\left(\frac{L_\infty}{L_\infty-L_0}\right) &= -K \\
-\frac{log\left(\frac{L_\infty}{L_\infty-L_0}\right)}{K} &= t
\end{align}
$$

The $\omega$ parameter was introduced into the fisheries growth modeling literature as $\omega=KL_\infty$ (CITATION). Thus, a starting value for $\omega$ is simply the product of $K$ and $L_\infty$ starting values.

A starting value for $t_50$ is derived (most easily) by solving the first parameterization equation for $t$ when $\frac{L}{L_\infty}=\frac{1}{2}$.

$$
\begin{align}
L &= L_\infty\left(1-e^{-K(t-t_0)}\right) \\
\frac{L}{L_\infty} &= 1-e^{-K(t-t_0)} \\
\frac{1}{2} &= 1-e^{-K(t_{50}-t_0)} \\
e^{-K(t_{50}-t_0)} &= \frac{1}{2} \\
-K(t_{50}-t_0) &= log\left(\frac{1}{2}\right) \\
t_{50}-t_0 &= \frac{log(2)}{K} \\
t_{50} &= t_0+\frac{log(2)}{K}
\end{align}
$$

A starting value for $L_r$ (i.e., mean length at time $t_r$) can be found by simply plugging $t_r$ into any parameterization^[Of course, one that does not include $t_r$ and has starting values for the other parameters. Using one of the first two parameterizations will suffice here.] and solving for $L$. This strategy generalizes to find starting values for $L_1$, $L_2$, and $L_3$.

A starting value for $t_r$ can be found by plugging $L_r$ for $L$ into any of the parameterizations and solving for $t$.

<br>

| Param | $L_\infty$ | $L_0$ | $K$ | $\omega$ | $t_0$ | $t_{50}$ |
|-------|-------|-------|-------|-------|-------|-------|
|   1   | $\text{Asym}$ | $\text{R0}$ | $e^{\text{lrc}}$ |  |  |  |
|   2   | $\text{Asym}$ | | $e^{\text{lrc}}$ |  | $-\frac{log\left(\frac{L_\infty}{L_\infty-L_0}\right)}{K}$ |  |
|   3   | $\text{Asym}$ | | $e^{\text{lrc}}$ | $KL_\infty$ |  |  |
|   4   | $\text{Asym}$ | $\text{R0}$ | | $KL_\infty$ |  |  |
|   5   | $\text{Asym}$ | | | | $-\frac{log\left(\frac{L_\infty}{L_\infty-L_0}\right)}{K}$ | $t_0+\frac{log(2)}{K}$ |
|   6   | $\text{Asym}$ | | $e^{\text{lrc}}$ | | | | | |
|   7   | | | $e^{\text{lrc}}$ | | | | |

: Conversion from `SSasymp()` parameters ($\text{Asym}$, $\text{R0}$, and $\text{lrc}$) to parameters for the common von Bertalanffy parameterizations used to model fish growth in `FSA`. Note that parameterizations 6, 7, 8, and 9 have other parameters not shown in this table (but described in the main text). {#tbl-VBstarts1}

<br>

## Seasonal Length-at-Age Data
### Parameterizations
There are also several parameterizations that include a seasonal component in the model such that age is not recorded annually @tbl-VBparams2

<br>

| param | Equation $L =$ |
|-------|-----------------------------------------------------|
|  10   | $L_\infty\left(1-e^{-K(t-t_0)-\frac{CK}{2\pi sin(2\pi(t-t_s))}+\frac{CK}{2\pi sin(2\pi(t_0-t_s))}}\right)$ |
|  11   | $L_\infty\left(1-e^{-K(t-t_0)-\frac{CK}{2\pi sin(2\pi(t-WP+0.5))}+\frac{CK}{2\pi sin(2\pi(t_0-WP+0.5))}}\right)$ |
|  12   | $L_\infty(1-e^{-q}$ with $q=K'(t'-t_0) + \frac{K'(1-NGT)}{2\pi}sin(\frac{2\pi}{(1-NGT)(t'-t_s)}) - \frac{K'(1-NGT)}{2\pi}sin(\frac{2\pi}{(1-NGT)(t_0-t_s)})$ |

: Parameterizations of the von Bertalanffy growth equation for length-at-age data with a seasonal component available in `FSA`. {#tbl-VBparams2}

<br>

Parameters in these growth functions are:^[One parameterization uses a modified time scale, symbolized with $t'$.]

- $C$ = proportional growth depression at "winter peak"
- $t_s$ = time from $t=0$ until first growth oscillation begins
- $WP$ = "winter peak" (point of slowest growth)
- $K'$ = exponential rate of approach to $L_\infty$ during the growth period
- $NGT$ = length of "no-growth period"



## Tag-Recapture Data
### The Parameterizations
Still other parameterizations of the von Bertalanffy model are used with tag-recapture data (@tbl-VBparams3).

| param | Equation |
|-------|-----------------------------------------------------|
|  13   | $a$ |
|  14   | $a$ |
|  15   | $a$ |
|  16   | $a$ |
|  17   | $a$ |
|  18   | $a$ |
|  19   | $a$ |

: Parameterizations of the von Bertalanffy growth equation for length at tag and recapture data available in `FSA` and their equations. {#tbl-VBparams3}



# Gompertz
## R Self-Starter Function
The `stats` package in base R contains `SSgompertz()` which is a self-starting function for using `nls()` to fit a Gompertz function to data. According to the documentation for `SSgompertz()` the parameterization of this function is

$$ Y = \text{Asym}~e^{-b_2b_3^X} $$

where $Y$ and $X$ are the response and explanatory variables, respectively, $\text{Asym}$ is a parameter for the horizontal (i.e., $Y$) asymptote, $b_2$ is a parameter related to the value of $Y$ at $X=0$, and $b_3$ is a "parameter related to the scale of the x-axis."

In growth (in length) modeling, $Y$ is $L$ (for length), $X$ is $t$ (for time as measured by age), and $\text{Asym}$ is clearly $L_{\infty}$. Thus, at this point, the R Gompertz function can be re-written for the purposes of growth modeling as 

$$ L = L_\infty e^{-b_2b_3^t} $$ {#eq-rSSgomp}

It is not immediately clear how $b_2$ and $b_3$ relate to parameters from common parameterizations of the Gompertz functions used to model fish growth. In the following sections I show how parameters in the common parameterizations of the Gompertz function relate to $b_2$ and $b_3$ (and, possibly, $L_{\infty}$). Understanding these relationships will allow use of `SSgompertz()` to derive starting values for $L_{\infty}$, $b_2$, and $b_3$ which can then be translated into starting values for the other parameterizations.

## "Ricker1" Paramaterization
The "Ricker1" parameterization implemented in `FSA` is

$$ L = L_\infty e^{-e^{-g_i(t-t_i)}} $$ {#eq-Ricker1}

where $t_i$ is the age at the inflection point and $g_i$ is the instantaneous growth rate at $t_i$.

The difference between @eq-Ricker1 and @eq-rSSgomp is completely after the negative in the exponent of $e$. Thus, I begin by algebraically simplifying this exponent.

$$
\begin{align}
& e^{-g_i(t-t_i)} \\
& e^{-g_it+g_it_i} \\
& e^{-g_it}e^{g_it_i} \\
& e^{g_it_i}e^{-g_it}
\end{align}
$$

If we define $b_2=e^{g_it_i}$ and $b_3=e^{-g_i}$, then this simplified exponent from @eq-Ricker1 is the same as the exponent in @eq-rSSgomp. Thus, $g_i=-log(b_3)$ and $t_i=\frac{log(b_2)}{g_i}$.

## "Ricker 2" or "Quinn-Deriso 1" Paramaterization
The "Ricker 2" or "Quinn-Deriso 1" parameterization implemented in `FSA` is

$$ L = L_0 e^{a(1-e^{-g_it})} $$ {#eq-Ricker2}

where $L_0$ is the mean length at $t=0$ (i.e., the y-intercept) and $a$ is a "nuisance" parameter with no particular biological or modeling meaning.

There is no asymptote in @eq-Ricker2 so the entire expressions must be manipulated to show equivalence to @eq-rSSgomp.

$$
\begin{align}
& L_0 e^{a(1-e^{-g_it})} \\
& L_0 e^{a-ae^{-g_it}} \\
& L_0 e^{a}e^{-ae^{-g_it}} \\
\end{align}
$$
If we define $L_\infty=L_0e^a$, $b_2=a$, and, again, $b_3=e^{-g_i}$ then @eq-Ricker2 is equivalent to @eq-rSSgomp. Thus, $a=b_2$, $g_i=-log(b_3)$, and $L_0=\frac{L_\infty}{e^a}$.

## "Ricker 3" or "Quinn-Deriso 2" Paramaterization
The "Ricker 3" or "Quinn-Deriso 2" parameterization implemented in `FSA` is

$$ L = L_\infty e^{-ae^{-g_it}} $$ {#eq-Ricker3}

Here it is obvious that $b_2=a$ and if we again define $b_3=e^{-g_i}$ then @eq-Ricker3 is equivalent to @eq-rSSgomp. Thus, $a=b_2$ and $g_i=-log(b_3)$.

## "Quinn-Deriso 3" Paramaterization
The "Quinn-Deriso 3" parameterization implemented in `FSA` is

$$ L = L_\infty e^{-\frac{1}{g_i}e^{-g_i(t-t_0)}} $$ {#eq-QD3}

where $t_0$ appears to be defined, as in the von Bertalanffy function, as the age where the mean length is zero. $t_0$ is an x-intercept, but the three-parameter Gompertz function used here has a lower asymptote at $L=0$ and, thus, does not have an x-intercept. Therefore, it is not exactly clear what $t_0$ is.

Again, the exponent (after the negative) of @eq-QD3 can be rearranged as follows

$$
\begin{align}
& \frac{1}{g_i}e^{-g_i(t-t_0)} \\
& \frac{1}{g_i}e^{-g_it+g_it_0} \\
& \frac{1}{g_i}e^{-g_it}e^{g_it_0} \\
& \frac{1}{g_i}e^{g_it_0}e^{-g_it}
\end{align}
$$

If we define $b_2=\frac{1}{g_i}e^{g_it_0}$ and $b_3=e^{-g_i}$, then this simplified exponent from @eq-QD3 is the same as the exponent in @eq-rSSgomp. Thus, $g_i=-log(b_3)$ and $t_0=\frac{log(b_2g_i)}{g_i}$.

## "Original" Paramaterization
The "Original" parameterization implemented in `FSA` is

$$ L = L_\infty e^{-e^{(a-g_it)}} $$ {#eq-Original}

Again, the exponent (after the negative) of @eq-Original can be rearranged as follows

$$
\begin{align}
& e^{(a-g_it)} \\
& e^{a}e^{-g_it)}
\end{align}
$$

If we define $b_2=e^a$ and $b_3=e^{-g_i}$, then this simplified exponent from @eq-Original is the same as the exponent in @eq-rSSgomp. Thus, $g_i=-log(b_3)$ and $a=log(b_2)$.

## Converting Conclusion

| Parameterization   | $L_\infty$ | $L_0$ | $g_i$ | $t_i$ | $t_0$ |  $a$  |
|--------------------|-------|-------|-------|-------|-------|-------|
| "Ricker 1"         | $\text{Asym}$ | | $-log(b_3)$ | $\frac{log(b_2)}{g_i}$ |  |  |
| "Ricker 2" / "QD1" |  | $\frac{L_\infty}{e^a}$ | $-log(b_3)$ |  |  | $b_2$ |
| "Ricker 3" / "QD2" | $\text{Asym}$ | | $-log(b_3)$ |  |  | $b_2$ |
| "QD3"              | $\text{Asym}$ | | $-log(b_3)$ |  | $\frac{log(b_2g_i)}{g_i}$ |  |
| "Original"         | $\text{Asym}$ | | $-log(b_3)$ |  |  | $log(b_2)$ |

: Conversion from `SSgompertz()` parameters ($\text{Asym}$, $b_2$, and $b_3$) to parameters for the common Gompertz parameterizations used to model fish growth in `FSA`. {#tbl-gompConvert}


# Logistic
## R Self-Starter Function
The `stats` package in base R contains `SSlogis()` which is a self-starting function for using `nls()` to fit a Gompertz function to data. According to the documentation for `SSlogis()` the parameterization of this function is

$$ Y = \frac{\text{Asym}}{1+e^{\frac{\text{xmid}-\text{input}}{\text{scal}}}} $$

where $Y$ and $\text{input}$ are the response and explanatory variables, respectively, $\text{Asym}$ is a parameter for the horizontal (i.e., $Y$) asymptote, $xmid$ is a parameter for the value of $X$ at the inflection point, and $scal$ is a "parameter on the input axis."

In growth (in length) modeling, $Y$ is $L$ (for length), $\text{input}$ is $t$ (for time as measured by age), and $\text{Asym}$ is clearly $L_{\infty}$. Most likely $xmid$ is $t_i$, but it is not 100% clear at this point. Thus, at this point, the R logistic function can be re-written for the purposes of growth modeling as 

$$ L = \frac{L_\infty}{1+e^{\frac{\text{xmid}-t}{\text{scal}}}} $$ {#eq-rSSlogis}

It is not immediately clear how $\text{scal}$ relates to parameters from common parameterizations of the logistic functions used to model fish growth. In the following sections I show how parameters in the common parameterizations of the logistic function relate to $\text{xmid}$ and $\text{scal}$ (and, possibly, $L_{\infty}$). Understanding these relationships will allow use of `SSlogis()` to derive starting values for $L_{\infty}$, $\text{xmid}$, and $\text{scal}$ which can then be translated into starting values for the other parameterizations.

For the explanations below, it will be easier if @eq-rSSlogis is presented in a more verbose form

$$
\begin{align}
L &= \frac{L_\infty}{1+e^{\frac{\text{xmid}-t}{\text{scal}}}} \\
  &= \frac{L_\infty}{1+e^{\frac{\text{xmid}}{\text{scal}}-\frac{t}{\text{scal}}}} \\
  &= \frac{L_\infty}{1+e^{\frac{\text{xmid}}{\text{scal}}}e^{-\frac{t}{\text{scal}}}}
\end{align}
$$ {#eq-rSSlogis1}


## Campana Jones 1 Parameterization
The "Campana and Jones 1" parameterization implemented in `FSA` is

$$ L = \frac{L_\infty}{1+e^{-g_{-\infty}(t-t_i)}} $$ {#eq-CJ1}

where $-g_{-\infty}$ is the instantaneous growth rate at $t=-\infty$.

The only difference between @eq-CJ1 and @eq-rSSlogis is in the denominator after the "1+". This portion can be rewritten as

$$
\begin{align}
& e^{-g_{-\infty}(t-t_i)} \\
& e^{-g_{-\infty}t+g_{-\infty}t_i} \\
& e^{-g_{-\infty}t}e^{g_{-\infty}t_i} \\
& e^{g_{-\infty}t_i}e^{-g_{-\infty}t}
\end{align}
$$

Comparing this to @eq-rSSlogis1 it becomes apparent that $g_{-\infty}=\frac{1}{\text{scal}}$ and $g_{-\infty}t_i=\frac{\text{xmid}}{\text{scal}}$. The latter can be simplified as

$$
\begin{align}
g_{-\infty}t_i &= \frac{\text{xmid}}{\text{scal}} \\
t_i &= \frac{\text{xmid}}{g_{-\infty}\text{scal}} \\
t_i &= \frac{\text{xmid}g_{-\infty}}{g_{-\infty}} \\
t_i &= \text{xmid}
\end{align}
$$

Thus, $\text{xmid}$ is the abcissa of the inflection point.

## Campana Jones 2 Parameterization
The "Campana and Jones 2" parameterization implemented in `FSA` is

$$ L = \frac{L_\infty}{1+ae^{-g_{-\infty}t}} $$ {#eq-CJ2}

where $a$ is a nuisance parameter without any real interpretation.

Again, the only difference between @eq-CJ2 and @eq-rSSlogis is in the denominator after the "1+", and no simplification is needed when comparing @eq-CJ2 to @eq-rSSlogis1 to notice that $g_{-\infty}=\frac{1}{\text{scal}}$ and $a=e^{\frac{\text{xmid}}{\text{scal}}}$.

## Karkach Parameterization
The "Karkach" parameterization implemented in `FSA` is

$$ L = \frac{L_0L_\infty}{L_0+(L_\infty - L_0)e^{-g_{-\infty}t}} $$ {#eq-Karkach}

Here we must rewrite the whole function first by dividing both the numerator and denominator by $L_0$ to get

$$ L = \frac{L_\infty}{1+\frac{L_\infty - L_0}{L_0}e^{-g_{-\infty}t}} $$

In this form the only difference from @eq-rSSlogis is again in the denominator after the "1+". Again, by comparing this to @eq-rSSlogis1, it is apparent that $g_{-\infty}=\frac{1}{\text{scal}}$ and $\frac{L_\infty - L_0}{L_0}=e^{\frac{\text{xmid}}{\text{scal}}}$. This second value is solved for $L_0$ with

$$
\begin{align}
\frac{L_\infty - L_0}{L_0} &= e^{\frac{\text{xmid}}{\text{scal}}} \\
L_\infty - L_0 &= L_0e^{\frac{\text{xmid}}{\text{scal}}} \\
L_\infty &= L_0 + L_0e^{\frac{\text{xmid}}{\text{scal}}} \\
L_\infty &= L_0\left(1+e^{\frac{\text{xmid}}{\text{scal}}}\right) \\
\frac{L_\infty}{1+e^{\frac{\text{xmid}}{\text{scal}}}} &= L_0
\end{align}
$$

## Converting Conclusion

| Parameterization    | $L_\infty$ | $L_0$ | $g_{-\infty}$ | $t_i$ |  $a$  |
|---------------------|-------|-------|-------|-------|-------|
| "Campana & Jones 1" | $\text{Asym}$ | | $\frac{1}{\text{scal}}$ | $\text{xmid}$ | |
| "Campana & Jones 2" | $\text{Asym}$ | | $\frac{1}{\text{scal}}$ | | $e^{\frac{\text{xmid}}{\text{scal}}}$ |
| "Karkach"           | $\text{Asym}$ | $\frac{L_\infty}{1+e^{\frac{\text{xmid}}{\text{scal}}}}$ | $\frac{1}{\text{scal}}$ | | |

: Conversion from `SSlogis()` parameters ($\text{Asym}$, $\text{xmid}$, and $\text{scal}$) to parameters for the common logistic parameterizations used to model fish growth in `FSA`. {#tbl-logisticConvert}


# Richards
The `FlexParamCurve` package in R contains `SSposnegRichards()` which is a self-starting function for using `nls()` to fit a "Positive-Negative Richards growth" function to data. This functions can fit an 8-parameter curve but if some of the parameters are not used then it is possible to fit a 4-parameter Richards curve, similar to what is done in `FSA`. Their "twelfth model" (i.e., `modno=12`) can be written, using their R function parameters, as

$$ Y = \frac{\text{Asym}}{\left[1+Me^{-K(X-\text{Infl})}\right]^{\frac{1}{M}}} $$
where $Y$ and $X$ are the response and explanatory variables, respectively, $\text{Asym}$ is a parameter for the horizontal (i.e., $Y$) asymptote, $K$ is a "rate parameter", $\text{Infl}$ is the "inflection point" (i.e., the x-axis position of the inflection point), and $M$ is a "shape parameter".

In growth (in length) modeling, $Y$ is $L$ (for length), $X$ is $t$ (for time as measured by age), and $\text{Asym}$ is clearly $L_{\infty}$. Thus, at this point, their function can be re-written for the purposes of growth modeling as 

$$ L = \frac{L_\infty}{\left[1+Me^{-K(t-\text{Infl})}\right]^{\frac{1}{M}}} $$

It is also likely that $\text{Infl}$ is equal to $t_i$, but we will explore this below.

## First Parameterization
The first parameterization of the Richards growth function implemented in `FSA` is

$$ L = \frac{L_\infty}{\left[1+b_1e^{-k(t-t_i)}\right]^\frac{1}{b_1}} $$ {#eq-Richards1}

where $t_i$ is the time (or age) of the inflection point and $b_1$ is a scaling factor.

There is no further work to be done here as a direct comparison of @eq-Richards1 to @rSSRichards shows that $b_1=M$, $k=K$, and $t_i=\text{Infl}$.

## Second Parameterization
The second parameterization of the Richards growth function implemented in `FSA` is

$$ L = \frac{L_\infty}{\left(1+e^{-k(t-t_0)}\right)^{-b_2}} $$ {#eq-Richards2}

NEED TO COME BACK TO THIS, BUT SOMEHOW I FOUND THAT

$t_0 = -\frac{log\left(\frac{1}{M}\right)}{K}+\text{Infl}$ and $b_2 = -\frac{1}{M}$


## Third Parameterization
The third parameterization of the Richards growth function implemented in `FSA` is

$$ L = L_\infty\left[1+\left(\left(\frac{L_0}{L_\infty}\right)^{1-b_3}-1\right)e^{-kt}\right]^\frac{1}{1-b_3} $$ {#eq-Richards3}

where $L_0$ is the mean length at $t=0$. As shown in the original reference (see `?RichardsFuns`) this parameterization was formed from setting $b_3=1+b_1$, so $b_3=1+M$. In addition, if $t$ is set to $0$ in @eq-Richards1 then $L_0=\frac{L_\infty}{\left[1+b_1e^{kt_i}\right]^\frac{1}{b_1}}$ such that $L_0$ can be estimated from the starting values of $L_\infty$, $k$, $t_i$, and $b_1$ from the first parameterization.

## Fourth Parameterization
The fourth parameterization of the Richards growth function implemented in `FSA` is

$$ L = L_\infty\left[1-\frac{1}{b_2}e^{-k(t-t_i)}\right]^{b_2} $$ {#eq-Richards4}

As shown in the original reference (see `?RichardsFuns`) this is exactly @eq-Richards1 with $b_2=-\frac{1}{b_1}$. Thus, from the work done for the first parameterization, $b_2=-\frac{1}{M}$, $k=K$, and $t_i=\text{Infl}$.


## Fifth Parameterization
The fifth parameterization of the Richards growth function implemented in `FSA` is

$$ L = L_\infty\left[1+(b_3-1)e^{-k(t-t_i)}\right]^\frac{1}{1-b_3} $$ {#eq-Richards5}

As shown in the original reference (see `?RichardsFuns`) this is exactly @eq-Richards1 with $b_3=1+b_1$. Thus, from the work done for the first parameterization, $b_3=1+M$, $k=K$, and $t_i=\text{Infl}$.


## Converting Conclusion

| Parameterization | $L_\infty$ | $L_0$ | $k$ | $t_i$ |  $t_0$  | $\text{b\#}$
|------------------|-------|-------|-------|-------|-------|-------|
| 1 | $\text{Asym}$ |  | $K$ | $\text{Infl}$ |  | $M$ |
| 2 | $\text{Asym}$ |  |  |  | $-\frac{log\left(\frac{1}{M}\right)}{K}+\text{Infl}$ | $-\frac{1}{M}$ |
| 3 | $\text{Asym}$ | $\frac{L_\infty}{\left[1+be^{kt_i}\right]^\frac{1}{b}}$ | $K$ |  |  | $1+M$ |
| 4 | $\text{Asym}$ |  | $K$ | $\text{Infl}$ |  | $-\frac{1}{M}$ |
| 5 | $\text{Asym}$ |  | $K$ | $\text{Infl}$ |  | $1+M$ |

: Conversion from `SSposnegRichards()` parameters ($\text{Asym}$, $\text{Infl}$, $K$, and $M$) to parameters for the common Richards parameterizations used to model fish growth in `FSA`. {#tbl-RichardsConvert}
